version: 2.1
orbs:
  ruby: circleci/ruby@1.4.1

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:2.6.9-node
    steps:
      - checkout
      - ruby/install-deps
      - run: gem install bundler
      - ruby/rspec-test

workflows:
  build_and_test_deploy:
    jobs:
      -build_and_test